name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1

    - name: Playwright GitHub Action
      uses: microsoft/playwright-github-action@v1

#    - name: Cache browsers
#      uses: actions/cache@v1
#      with:
#        path: '~/.cache/ms-playwright/'
#        key: ${{ runner.os }}-browsers

    - name: Setup
      run: mkdir artifacts

    - name: Install dependencies
      uses: bahmutov/npm-install@v1

    - name: Run tests
      run: npm test
      env:
        CI: true

    - name: Check browsers
      run: ls -alh ~/.cache/ms-playwright/

    - uses: actions/upload-artifact@v2
      with:
        name: my-artifacts
        path: artifacts/
    - uses: actions/upload-artifact@v2
      with:
        name: example-chromium.png
        path: artifacts/example-chromium.png
    - uses: actions/upload-artifact@v2
      with:
        path: artifacts/example-firefox.png